version: "3"

networks:
    ewd_net:
        driver: ipvlan
        driver_opts:
            parent: wlp2s0
        ipam:
            config:
                - subnet: 10.10.7.0/24
                  gateway: 10.10.7.1


x-serviceDef: &serviceDef
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    security_opt:
      - apparmor:unconfined  # Allows DBus
    volumes:
      - /var/run/dbus/:/var/run/dbus/:ro  # Mounts DBus (on Ubuntu at least)

services:
    receiver_1:
        <<: *serviceDef
        networks:
            ewd_net:
                ipv4_address: 10.10.7.59
        environment:
            - EWD_NAME=Voc RF4
            - EWD_MAC_ADDRESS=E1:CA:D0:2E:B6:71
